### ISSUE TITLE
possibility of changing the player

### ISSUE THREAD

**Issue by bachig26** [FlamesX-128/anigo#10]
I want to ask if there is possibility of supporting other players, as to manually defined the user prefered media player as default instead of mpv.

like, I use extensively [MPC-BE](https://github.com/Aleksoid1978/MPC-BE), if the support for this player and user defining the player/path would nice.

**Comment by FlamesX-128** [comment]
It is something that I already had in mind, I will probably add it in the future.

https://github.com/FlamesX-128/anigo/discussions/9
