### ISSUE TITLE
[improvement] quality settings

### ISSUE THREAD

**Issue by bachig26** [FlamesX-128/anigo#11]
currently, the quality/ resolution of the content is selected manually every time. it would be nice to have them pre-defined.

**example:
so, if there is an option to preset the quality (say 720p), and this quality is played for every stream of anime/content that I'm playing without going through the quality selector option.
also, in addition to this, an option for quality fallback incase the preset quality is no present.**

**Comment by FlamesX-128** [comment]
maybe i will add it when i rewrite anigo.
