### ISSUE TITLE
[Suggestion] ability to have command options

### ISSUE THREAD

**Issue by bachig26** [FlamesX-128/anigo#12]
I know this is stretch, is there any possibility to have command option method (similar to yt-dlp or other) in addition to the current tree selection option.

this suggestion, i just thought of while going through between two programs...i know this is too much, just wanted to ask about this because as you may know or maynot i'm not good these things on the side of programming.

**Comment by FlamesX-128** [comment]
@bachig26 
![image](https://user-images.githubusercontent.com/78381898/201732999-bb079ae7-1744-4be1-b0bd-29da9ee15e1a.png)
flag commands?

**Comment by bachig26** [comment]
> flag commands?

yes

**Comment by FlamesX-128** [comment]
@bachig26 " in addition to the current tree selection option." can you give me an example?

**Comment by bachig26** [comment]
> @bachig26 " in addition to the current tree selection option." can you give me an example?

I mean the current structure, i don't know how to describe it as i don't know the name.

```
Î» anigo@integrated-win@amd64
? Select an option Search
? Select a provider [API] [Direct] GoGoAnime
? what novel do you want to look for? bleach

? what novel do you want to look for? bleach
? which novel do you want to select?  [Use arrows to move, type to filter]
> Bleach: The Sealed Sword Frenzy
  Bleach OVA
  Bleach The Movie 3: Fade to Black (Dub)
  Bleach Movie 2: The Diamond Dust Rebellion
  Bleach The Movie 2: The DiamondDust Rebellion (Dub)
  Bleach the Movie 4: Hell Verse (Dub)
  Bleach: Memories in the Rain
```

**Comment by FlamesX-128** [comment]
the flag commands is something that I was going to add in the future, but I don't understand the other part you say 🤔

**Comment by bachig26** [comment]
> the flag commands is something that I was going to add in the future, but I don't understand the other part you say 🤔

@FlamesX-128 i mean by, the current structure is like selecting one option (example: plugin) and it will branch out to other option (example: quality, which has multiple options to select like 720p, 1080p, 360p, etc.)

i find it looks like a tree extending into branch's, so i mentioned it as tree like structure options.


ps. just a figure of speech, not much

**Comment by FlamesX-128** [comment]
- option 1
- option 2 - selected
  + option 3 - selected
     * option 4
     * option 5
  + option 6
  + option 7
- option 8
:thinking:

**Comment by bachig26** [comment]
> * option 1
> * option 2 - selected
>   
>   * option 3 - selected
>     
>     * option 4
>     * option 5
>   * option 6
>   * option 7
> * option 8
>   🤔

yeah, that's what i mean by that as how it currently looks.

**Comment by FlamesX-128** [comment]
I'll keep it in mind, but probably the console interfaces that there are problems for it.
